#!/bin/sh

# hack until there's an actual test suite
./bin/juici &
juici_pid=$!

python test/emit_proto.py --workspace "butts" \
                          --title "butts" \
                          --command "echo 'butts' > test/butts_out" \
    | socat - /tmp/juici.sock

wait $juici_pid
exit $?
